### ISSUE TITLE
Difficulties generating reasonable actions

### ISSUE THREAD

**Issue by jadenvc** [MichalZawalski/embodied-CoT#2]
I followed the Embodied CoT reasoning example notebook, loading in the model with the following code:

path_to_converted_ckpt = "Embodied-CoT/ecot-openvla-7b-bridge"
processor = AutoProcessor.from_pretrained(path_to_converted_ckpt, trust_remote_code=True)
vla = AutoModelForVision2Seq.from_pretrained(
    path_to_converted_ckpt,
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    trust_remote_code=True,
    # [Optional] Set `load_in_4bit=True` if not enough GPU memory + run `pip install bitsandbytes`
    # Then, comment out `.to(device)`
).to(device)

and the provided prompt. I used this code to generate actions:

action, generated_ids = vla.predict_action(**inputs, unnorm_key="bridge_orig", do_sample=False, max_new_tokens=1024)
generated_text = processor.batch_decode(generated_ids)[0].

This produces good task reasonings. However, when I run the model on various bridge tasks and images (offline) I am not able to get the model to generate reasonable actions. For example, the gripper seems to never close and the actions differ greatly from both ground truth actions and OpenVLA outputs. I first tried Embodied CoT on the simpler env widowx tasks, and the gripper always drifts off screen, whereas OpenVLA generates good actions - with up 50% task success on the place eggplant task (embodied cot always 0% success).

I also ran the model on images/rollouts from various bridge tasks offline, to see how well Embodied CoT matched ground truth action and OpenVLA actions. On the task "take the blue spoon off the burner and put it on the right side of the burner", Embodied CoT had average L2 norm vs ground turth actions of 0.44, whereas openVLA had 0.16. I found that even although Embodied CoT generates the correct reasonings most of the time for this task, the actions are not alight; ie when the move reasoning is "close gripper" the action is not to close the gripper. This appears to be an action normalization issue, as the index 5 of the action appears to be the gripper action, and index 0 appears to be flipped. How should the actions be correctly processed?

**Comment by smirchan** [comment]
I'm wondering if it's an issue related to a difference between `predict_action` on HuggingFace in `OpenVLAForActionPrediction` versus `predict_action` in `openvla.py`.

Specifically, it looks like this operation (https://github.com/MichalZawalski/embodied-CoT/blob/22244869fe449d4f47b5234cae752d1e7e03f94e/prismatic/models/vlas/openvla.py#L207) occurs in `openvla.py` before action denormalization

but not here (https://huggingface.co/Embodied-CoT/ecot-openvla-7b-oxe/blob/bcc12ab58303ee2d6da5ca1be4efc4d9914d8354/modeling_prismatic.py#L518)

Could this be the issue?

**Comment by verityw** [comment]
So true bestie, just updated the HF model s.t. actions now take
```
predicted_action_token_ids = generated_ids[0, -(self.get_action_dim(unnorm_key) + 1) : -1].cpu().numpy()
```
(so final 7 tokens other than the EOS token).

With that change, the example inference from the Colab notebook now produces the actions:
`[ 0.01321167, -0.03668522,  0.00027841, -0.0205739 , -0.02891492, -0.08065662,  0.        ]`
instead of 
`[-0.0252603  -0.00884188 -0.00154037 -0.0199353  -0.04030262 -0.00167851 0.99607843]`
which should be correct (the last term being open / close gripper should only ever be 0, 1)

Thanks for catching this!
