### ISSUE TITLE
How to fine-tune the openvla-7b using Bridge-V2 dataset and to reproduce ECoT with given json data?

### ISSUE THREAD

**Issue by betray12138** [MichalZawalski/embodied-CoT#4]
Thankfully for the open-source of your great work! However, I'm confused that in your github readme, I can only see how to train the openvla from scratch with the dataset Open-X-Embodiment and I also check this from the code of vla-scripts/train.py. Could you please tell me how to fine-tune the openvla-7b using Bridge-V2 dataset and to reproduce ECoT with your given reasoning (json file)? Sincerely thanks for your help!

**Comment by MichalZawalski** [comment]
Hi, all you have to do is to link the downloaded reasonings file. By default, the code assumes it's in `~/.cache/reasonings_dataset.json`. You can either manually specify the path in https://github.com/MichalZawalski/embodied-CoT/blob/main/prismatic/vla/datasets/rlds/dataset.py#L60, or update the training configuration that you use (in https://github.com/MichalZawalski/embodied-CoT/blob/main/prismatic/conf/vla.py), or specify the path in the training command as an additional argument.
