### ISSUE TITLE
Is there any plan to report your results on simulation?

### ISSUE THREAD

**Issue by GuanxingLu** [MichalZawalski/embodied-CoT#8]
Congrats on your great work! I would like to ask is there any plan to report your results on simulation (like LIBERO, as reported in the original openvla paper)?

**Comment by MichalZawalski** [comment]
Thanks a lot! At the moment, we don’t have plans to run additional experiments in simulation environments. That said, given the generality of our method, it should indeed perform well in such setups, and we’d be very curious to see the results if someone explores this further.

One potential challenge in simulations could be that the VLMs we used to extract embodied features might not be equally well trained for simulated scenes. However, simulations do offer the advantage of accessing features directly from the state information. This could also allow for an investigation into ECoT’s sensitivity to the quality of the extracted features, which would be a fascinating direction to explore.
